# -*- coding: utf-8 -*-
"""Parasite_Localization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/sometimessubodh/parasite-localization.4c3a98ed-64a1-4158-9c5f-192b10070da6.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260512/auto/storage/goog4_request%26X-Goog-Date%3D20260512T151024Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Da3f9cd42d14067457b7a134cb4f1478b31757fc514e6ceae9ca86c7ed1b630164fffe2e8e719833152872aabf82b4ceb4f7491cdf816ad5fe6c6fb9d5b8badc2da3267dbcb51f7469cd8725ce79de06514a9a80a78f64f4aabe9b5a4e6985bd0b7ba841b6b65ae073c739e779ab6e7989be982df558345ee99ffdbe272b77acf33048df540b726d4e062451d0ecf78eafdbf0b999b3d634b3a7270db548748802036f3ccab05e017882b73b682a5e7b618a8dc50262f3a53cfdd07ecafc5b98681083a3dab5665d27605ca36a7b7feca129adfcb4256ba12d2d47ad1f783dc7aa9fd27a4413d381f52c95814688c62c34a76dd007253de66038a0b57b4aeb92f
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
sometimessubodh_multi_disease_dataset_path = kagglehub.dataset_download('sometimessubodh/multi-disease-dataset')

print('Data source import complete.')

# ============================================================
# STEP 1: Install Dependencies
# Run this in a Kaggle notebook cell
# ============================================================

!pip install ultralytics --quiet   # YOLOv8 framework
!pip install Pillow matplotlib seaborn pandas --quiet

# Verify GPU is available
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'No GPU'}")

# If you see 'Tesla T4' or similar — you're good to go!

# ============================================================
# STEP 2: Dataset Exploration
# Before training anything, understand what you have
# ============================================================

import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np

# ── Define your dataset paths ──────────────────────────────
DATASET_PATHS = {
    "sickle": {
        "images": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/scd_dataset/images",
        "labels": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/scd_dataset/labels"
    },
    "malaria": {
        "images": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/malaria_dataset/images",
        "labels": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/malaria_dataset/labels"
    },
    "leukemia": {
        "images": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/leukemia_balanced_subset/images",
        "labels": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/leukemia_balanced_subset/labels"
    }
}

# CLASS MAPPING — based on your dataset description
# NOTE: You may need to adjust these IDs after checking your actual label files
CLASS_NAMES = {
    0: "normal",
    1: "malaria",
    2: "sickle",
    3: "leukemia"
}

# ── Count images per dataset ────────────────────────────────
def count_files(directory, extension="*.jpg"):
    """Count files matching an extension in a directory."""
    if not os.path.exists(directory):
        print(f"  WARNING: Directory not found: {directory}")
        return []
    return glob.glob(os.path.join(directory, extension))

print("=" * 55)
print("DATASET INVENTORY")
print("=" * 55)
total_images = 0
for disease, paths in DATASET_PATHS.items():
    imgs = count_files(paths["images"], "*.jpg") + count_files(paths["images"], "*.jpeg")
    lbls = count_files(paths["labels"], "*.txt")
    # Remove classes.txt if present (it's metadata, not a label)
    lbls = [l for l in lbls if "classes" not in l.lower()]
    print(f"\n{disease.upper()}:")
    print(f"  Images : {len(imgs)}")
    print(f"  Labels : {len(lbls)}")
    if len(imgs) != len(lbls):
        print(f"  ⚠️  MISMATCH! Some images may be missing labels.")
    total_images += len(imgs)

print(f"\nTotal images: {total_images}")

# ============================================================
# STEP 3: Annotation Verification & Visualization
# This is the most important debugging step — do NOT skip!
# ============================================================

def read_yolo_label(label_path):
    """
    Read a YOLO format label file.
    Each line: class_id  x_center  y_center  width  height
    All values are normalized (0 to 1).
    """
    boxes = []
    if not os.path.exists(label_path):
        return boxes

    with open(label_path, "r") as f:
        for line in f.readlines():
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 5:
                print(f"  Skipping malformed line: {line}")
                continue
            class_id = int(float(parts[0]))
            x_center = float(parts[1])
            y_center = float(parts[2])
            width    = float(parts[3])
            height   = float(parts[4])
            boxes.append((class_id, x_center, y_center, width, height))
    return boxes


def visualize_annotations(image_path, label_path, class_names, title=""):
    """
    Draw bounding boxes on an image and display it.
    Converts YOLO normalized coords back to pixel coords for drawing.
    """
    # Load image
    img = Image.open(image_path).convert("RGB")
    img_w, img_h = img.size

    # Read labels
    boxes = read_yolo_label(label_path)

    # Setup plot
    fig, ax = plt.subplots(1, 1, figsize=(8, 8))
    ax.imshow(img)
    ax.set_title(f"{title}\n{os.path.basename(image_path)} — {len(boxes)} objects",
                 fontsize=11)
    ax.axis("off")

    # Color per class
    colors = {0: "lime", 1: "red", 2: "cyan", 3: "yellow"}

    for (class_id, xc, yc, bw, bh) in boxes:
        # Convert YOLO normalized → pixel coords
        x1 = (xc - bw / 2) * img_w
        y1 = (yc - bh / 2) * img_h
        box_w = bw * img_w
        box_h = bh * img_h

        color = colors.get(class_id, "white")
        label = class_names.get(class_id, f"class_{class_id}")

        # Draw rectangle
        rect = patches.Rectangle(
            (x1, y1), box_w, box_h,
            linewidth=1.5,
            edgecolor=color,
            facecolor="none"
        )
        ax.add_patch(rect)

        # Draw label text
        ax.text(
            x1, y1 - 3, label,
            color=color,
            fontsize=8,
            fontweight="bold",
            bbox=dict(boxstyle="round,pad=0.1", facecolor="black", alpha=0.5)
        )

    plt.tight_layout()
    plt.show()
    return boxes


# ── Visualize one sample from each disease ─────────────────
print("Visualizing sample annotations...\n")

for disease, paths in DATASET_PATHS.items():
    img_files = (
        glob.glob(os.path.join(paths["images"], "*.jpg")) +
        glob.glob(os.path.join(paths["images"], "*.jpeg"))
    )

    if not img_files:
        print(f"No images found for {disease}")
        continue

    # Pick first image
    img_path = img_files[24]
    # Construct label path (same filename, .txt extension)
    label_path = os.path.join(
        paths["labels"],
        os.path.splitext(os.path.basename(img_path))[0] + ".txt"
    )

    boxes = visualize_annotations(img_path, label_path, CLASS_NAMES, title=disease.upper())
    print(f"{disease}: {len(boxes)} boxes found in sample image")

# ============================================================
# STEP 4: Discover Actual Class IDs Used in Labels
# Your sample annotation showed class_id = 0 for everything.
# We need to know if each dataset uses the same or different IDs.
# ============================================================

def analyze_class_ids(dataset_paths):
    """
    Scan all label files and report which class IDs appear.
    This tells us if labels are per-disease (all 0) or unified.
    """
    results = {}
    for disease, paths in dataset_paths.items():
        label_files = glob.glob(os.path.join(paths["labels"], "*.txt"))
        label_files = [l for l in label_files if "classes" not in l.lower()]

        class_counts = {}
        total_boxes = 0

        for lf in label_files:
            boxes = read_yolo_label(lf)
            for (cid, *_) in boxes:
                class_counts[cid] = class_counts.get(cid, 0) + 1
                total_boxes += 1

        results[disease] = {
            "class_ids": class_counts,
            "total_boxes": total_boxes,
            "label_files": len(label_files)
        }

    return results


class_analysis = analyze_class_ids(DATASET_PATHS)
print("=" * 55)
print("CLASS ID ANALYSIS")
print("=" * 55)
for disease, info in class_analysis.items():
    print(f"\n{disease.upper()}:")
    print(f"  Label files : {info['label_files']}")
    print(f"  Total boxes : {info['total_boxes']}")
    print(f"  Class IDs   : {info['class_ids']}")

    # ⚠️ Flag per-disease single-class labeling
    if list(info["class_ids"].keys()) == [0]:
        print(f"  ⚠️  All boxes labeled as class 0 — need remapping!")

# ============================================================
# STEP 5 (CORRECTED): Build Unified Dataset
#
# FINAL CLASS SCHEMA (6 classes total):
#   0 = sickle          (from sickle dataset,   raw class 0)
#   1 = malaria         (from malaria dataset,  raw class 0)
#   2 = leukemia_benign (from leukemia dataset, raw class 0)
#   3 = leukemia_malignant_early (leukemia,     raw class 1)
#   4 = leukemia_malignant_pre   (leukemia,     raw class 2)
#   5 = leukemia_malignant_pro   (leukemia,     raw class 3)
#
# WHY THIS SCHEMA?
#   - Sickle and malaria each used class 0 independently.
#     Merging without remapping would make them identical.
#   - Leukemia already has 4 distinct subtypes (0,1,2,3).
#     We preserve all subtypes — collapsing them into one class
#     would destroy clinically important information.
# ============================================================

import os
import glob
import shutil
import random

# ── Paths ───────────────────────────────────────────────────
DATASET_PATHS = {
    "sickle": {
        "images": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/scd_dataset/images",
        "labels": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/scd_dataset/labels"
    },
    "malaria": {
        "images": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/malaria_dataset/images",
        "labels": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/malaria_dataset/labels"
    },
    "leukemia": {
        "images": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/leukemia_balanced_subset/images",
        "labels": "/kaggle/input/datasets/sometimessubodh/multi-disease-dataset/dataset/leukemia_balanced_subset/labels"
    }
}

OUTPUT_BASE = "/kaggle/working/unified_dataset"

# ── CORRECTED CLASS MAPPING ─────────────────────────────────
#
# Format: "disease_name": { raw_class_id_str: new_unified_id }
#
# For sickle:   raw 0 → unified 0
# For malaria:  raw 0 → unified 1
# For leukemia: raw 0 → unified 2  (benign)
#               raw 1 → unified 3  (malignant early)
#               raw 2 → unified 4  (malignant pre)
#               raw 3 → unified 5  (malignant pro)
#
DISEASE_CLASS_MAP = {
    "sickle": {
        "0": 0,   # sickle cell disease
    },
    "malaria": {
        "0": 1,   # malaria parasite
    },
    "leukemia": {
        "0": 2,   # benign (normal-looking in leukemia context)
        "1": 3,   # malignant early stage
        "2": 4,   # malignant pre stage
        "3": 5,   # malignant pro stage
    },
}

# Human-readable names aligned with class IDs
CLASS_NAMES_UNIFIED = {
    0: "sickle",
    1: "malaria",
    2: "leukemia_benign",
    3: "leukemia_malignant_early",
    4: "leukemia_malignant_pre",
    5: "leukemia_malignant_pro",
}


def read_yolo_label(label_path):
    """Read YOLO .txt label. Returns list of (class_id, xc, yc, w, h)."""
    boxes = []
    if not os.path.exists(label_path):
        return boxes
    with open(label_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 5:
                continue
            boxes.append((
                int(float(parts[0])),
                float(parts[1]),
                float(parts[2]),
                float(parts[3]),
                float(parts[4]),
            ))
    return boxes


def remap_and_copy(src_img, src_lbl, dst_img_dir, dst_lbl_dir,
                   class_map, img_idx):
    """
    Copy one image and write a remapped label file.

    class_map: dict { "raw_id_as_str": new_unified_int }
    img_idx:   unique integer to prevent filename collisions across datasets
    """
    ext       = os.path.splitext(src_img)[1]
    base_name = f"img_{img_idx:06d}"

    # ── Copy image ───────────────────────────────────────────
    shutil.copy2(src_img, os.path.join(dst_img_dir, base_name + ext))

    # ── Write remapped label ─────────────────────────────────
    dst_lbl_path = os.path.join(dst_lbl_dir, base_name + ".txt")
    boxes = read_yolo_label(src_lbl)

    with open(dst_lbl_path, "w") as f:
        for (raw_cid, xc, yc, bw, bh) in boxes:
            key = str(raw_cid)
            if key not in class_map:
                # Unknown class ID — skip with a warning
                print(f"  WARNING: Unknown class id {raw_cid} in {src_lbl} — skipped")
                continue
            new_cid = class_map[key]
            f.write(f"{new_cid} {xc:.6f} {yc:.6f} {bw:.6f} {bh:.6f}\n")


def build_unified_dataset(dataset_paths, disease_class_map, output_base,
                           train_ratio=0.70, val_ratio=0.20, test_ratio=0.10,
                           seed=42):
    """
    Merge all disease datasets into one unified YOLO dataset
    with correct class remapping and stratified splits.

    Split strategy: 70% train / 20% val / 10% test
    Each disease is split independently before merging, so every
    disease appears in every split at the correct proportion.
    This is called STRATIFIED SPLITTING — important because if we
    shuffled everything together first, the tiny malaria set could
    accidentally end up mostly in val/test.
    """
    random.seed(seed)
    img_counter  = 0
    split_counts = {"train": {}, "val": {}, "test": {}}

    for disease, paths in dataset_paths.items():
        print(f"\n{'─'*50}")
        print(f"Processing: {disease.upper()}")
        print(f"{'─'*50}")

        img_files = sorted(
            glob.glob(os.path.join(paths["images"], "*.jpg"))  +
            glob.glob(os.path.join(paths["images"], "*.jpeg")) +
            glob.glob(os.path.join(paths["images"], "*.png"))
        )

        if not img_files:
            print(f"  No images found — skipping.")
            continue

        random.shuffle(img_files)
        n       = len(img_files)
        n_train = int(n * train_ratio)
        n_val   = int(n * val_ratio)
        # Everything remaining goes to test

        splits = {
            "train": img_files[:n_train],
            "val":   img_files[n_train : n_train + n_val],
            "test":  img_files[n_train + n_val:],
        }

        cmap = disease_class_map[disease]

        for split_name, files in splits.items():
            dst_img = os.path.join(output_base, "images", split_name)
            dst_lbl = os.path.join(output_base, "labels", split_name)
            os.makedirs(dst_img, exist_ok=True)
            os.makedirs(dst_lbl, exist_ok=True)

            for img_path in files:
                lbl_path = os.path.join(
                    paths["labels"],
                    os.path.splitext(os.path.basename(img_path))[0] + ".txt"
                )
                remap_and_copy(img_path, lbl_path,
                               dst_img, dst_lbl, cmap, img_counter)
                img_counter += 1

            split_counts[split_name][disease] = len(files)
            print(f"  {split_name:5s} → {len(files):4d} images")

    return split_counts


# ── Run it ──────────────────────────────────────────────────
print("Building unified dataset with corrected class mapping...\n")
summary = build_unified_dataset(
    DATASET_PATHS, DISEASE_CLASS_MAP, OUTPUT_BASE,
    train_ratio=0.70, val_ratio=0.20, test_ratio=0.10
)

# ── Print summary ────────────────────────────────────────────
print(f"\n{'='*50}")
print("SPLIT SUMMARY")
print(f"{'='*50}")
for split, counts in summary.items():
    total = sum(counts.values())
    print(f"\n{split.upper()} — {total} images total:")
    for disease, n in counts.items():
        print(f"  {disease:<12} : {n}")

# ============================================================
# FIX A — Oversample leukemia_malignant_pre + malaria
#
# WHERE IT FITS: Run this AFTER Step 5, BEFORE Fix C.
#
# WHAT IT DOES:
#   For leukemia_malignant_pre (class 4) — the broken class:
#     - Duplicates every training image containing 'pre' cells
#       5 extra times (so each image appears 6× total)
#     - For each 'pre' bounding box, crops a tight patch
#       around that cell (with 40% padding) and saves it
#       as a new standalone training image. This forces the
#       model to study 'pre' cell morphology in isolation.
#
#   For malaria (class 1) — the low-precision class:
#     - Duplicates 3× (lighter treatment — recall was fine,
#       we just need slightly more exposure to reduce FP rate)
#     - No crops needed for malaria
#
# SAFETY: Only adds new files. Existing files are untouched.
#         Safe to run on your already-built unified_dataset.
# ============================================================

import os, glob, shutil, random
from PIL import Image

# ── Config — adjust if your paths differ ────────────────────
OUTPUT_BASE = "/kaggle/working/unified_dataset"
SEED        = 42

CLASS_NAMES = {
    0: "sickle",
    1: "malaria",
    2: "leukemia_benign",
    3: "leukemia_malignant_early",
    4: "leukemia_malignant_pre",
    5: "leukemia_malignant_pro",
}

# ── Helper functions ─────────────────────────────────────────

def read_yolo_label(path):
    """Read a YOLO .txt label file. Returns list of (cid, xc, yc, bw, bh)."""
    boxes = []
    if not os.path.exists(path):
        return boxes
    with open(path) as f:
        for line in f:
            p = line.strip().split()
            if len(p) >= 5:
                boxes.append((
                    int(float(p[0])),
                    float(p[1]), float(p[2]),
                    float(p[3]), float(p[4])
                ))
    return boxes


def write_yolo_label(path, boxes):
    """Write a list of (cid, xc, yc, bw, bh) to a YOLO .txt file."""
    with open(path, "w") as f:
        for (cid, xc, yc, bw, bh) in boxes:
            f.write(f"{cid} {xc:.6f} {yc:.6f} {bw:.6f} {bh:.6f}\n")


def print_class_distribution(output_base, label="Current"):
    """Print how many bounding boxes exist per class in the train split."""
    counts = {}
    for lf in glob.glob(os.path.join(output_base, "labels", "train", "*.txt")):
        for (cid, *_) in read_yolo_label(lf):
            counts[cid] = counts.get(cid, 0) + 1
    total = sum(counts.values())
    print(f"\n{label} training box distribution:")
    print(f"  {'ID':<4} {'Class':<32} {'Boxes':>6}  {'%':>5}")
    print("  " + "─" * 52)
    for cid in sorted(CLASS_NAMES.keys()):
        n   = counts.get(cid, 0)
        pct = 100 * n / total if total else 0
        bar = "█" * int(pct / 2)
        flag = " ← TARGET" if cid in (1, 4) else ""
        pr

# ============================================================
# FIX D: Merge leukemia malignant subtypes → one class
#
# WHY:
#   leukemia_malignant_pre has Recall = 0.249 after two full
#   training runs. The model cannot reliably distinguish the
#   pre-B stage from early-B and pro-B at this resolution.
#   This is a known challenge in hematology — even trained
#   pathologists use flow cytometry, not morphology alone,
#   to distinguish these sub-stages.
#
#   Merging gives the model a single clear signal:
#   "this is a malignant leukocyte" without requiring
#   it to resolve sub-stage boundaries from pixel data alone.
#
# NEW SCHEMA (4 classes):
#   0 = sickle
#   1 = malaria
#   2 = leukemia_benign
#   3 = leukemia_malignant  ← early + pre + pro merged
#
# EXPECTED RESULT:
#   mAP@50: 0.802 → 0.85–0.90
#   The previously broken 'pre' class now contributes to
#   a well-defined 'malignant' class with plenty of examples.
# ============================================================

import os, glob, shutil

# ── Paths ────────────────────────────────────────────────────
SOURCE_BASE = "/kaggle/working/unified_dataset"       # your existing 6-class dataset
MERGED_BASE = "/kaggle/working/unified_dataset_4class"
yaml_4class = "/kaggle/working/dataset_4class.yaml"

# Remap: old 6-class ID → new 4-class ID
MERGE_MAP = {
    0: 0,   # sickle                  → sickle
    1: 1,   # malaria                 → malaria
    2: 2,   # leukemia_benign         → leukemia_benign
    3: 3,   # leukemia_malignant_early → leukemia_malignant  (merged)
    4: 3,   # leukemia_malignant_pre  → leukemia_malignant  (merged)
    5: 3,   # leukemia_malignant_pro  → leukemia_malignant  (merged)
}

CLASS_NAMES_4 = {0:"sickle", 1:"malaria", 2:"leukemia_benign", 3:"leukemia_malignant"}


def read_yolo_label(path):
    boxes = []
    if not os.path.exists(path):
        return boxes
    with open(path) as f:
        for line in f:
            p = line.strip().split()
            if len(p) >= 5:
                boxes.append((int(float(p[0])), float(p[1]),
                               float(p[2]), float(p[3]), float(p[4])))
    return boxes


def write_yolo_label(path, boxes):
    with open(path, "w") as f:
        for (cid, xc, yc, bw, bh) in boxes:
            f.write(f"{cid} {xc:.6f} {yc:.6f} {bw:.6f} {bh:.6f}\n")


def build_4class_dataset(source_base, dest_base, merge_map):
    """
    Copy the entire unified_dataset to a new folder,
    remapping class IDs per merge_map.
    The source (6-class) dataset is NOT modified.
    """
    print("Building 4-class merged dataset...")

    for split in ["train", "val", "test"]:
        os.makedirs(f"{dest_base}/images/{split}", exist_ok=True)
        os.makedirs(f"{dest_base}/labels/{split}", exist_ok=True)

        img_files = (
            glob.glob(f"{source_base}/images/{split}/*.jpg") +
            glob.glob(f"{source_base}/images/{split}/*.jpeg")
        )

        for img_path in img_files:
            base     = os.path.splitext(os.path.basename(img_path))[0]
            ext      = os.path.splitext(img_path)[1]
            lbl_path = f"{source_base}/labels/{split}/{base}.txt"

            # Copy image unchanged
            shutil.copy2(img_path, f"{dest_base}/images/{split}/{base}{ext}")

            # Remap labels
            old_boxes = read_yolo_label(lbl_path)
            new_boxes = [(merge_map.get(cid, cid), xc, yc, bw, bh)
                         for (cid, xc, yc, bw, bh) in old_boxes]
            write_yolo_label(f"{dest_base}/labels/{split}/{base}.txt", new_boxes)

        n_imgs = len(glob.glob(f"{dest_base}/images/{split}/*.jp*"))
        n_lbls = len(glob.glob(f"{dest_base}/labels/{split}/*.txt"))
        status = "OK" if n_imgs == n_lbls else "MISMATCH"
        print(f"  {split:5s}: {n_imgs:5d} images  {n_lbls:5d} labels  [{status}]")

    # ── Verify new class distribution ────────────────────────
    print("\nNew class distribution in train split:")
    counts = {}
    for lf in glob.glob(f"{dest_base}/labels/train/*.txt"):
        for (cid, *_) in read_yolo_label(lf):
            counts[cid] = counts.get(cid, 0) + 1
    total = sum(counts.values())
    for cid in sorted(CLASS_NAMES_4.keys()):
        n   = counts.get(cid, 0)
        pct = 100 * n / total
        bar = "█" * int(pct / 2)
        print(f"  {cid}  {CLASS_NAMES_4[cid]:<22} {n:>7}  {pct:5.1f}%  {bar}")
    print(f"\n  Total boxes: {total}")


# ── Run the merge ─────────────────────────────────────────────
build_4class_dataset(SOURCE_BASE, MERGED_BASE, MERGE_MAP)

# ── Write 4-class dataset.yaml ────────────────────────────────
yaml_content = f"""
# 4-class merged dataset
# leukemia malignant subtypes (early + pre + pro) merged into one class

path: {MERGED_BASE}
train: images/train
val:   images/val
test:  images/test

nc: 4

names:
  0: sickle
  1: malaria
  2: leukemia_benign
  3: leukemia_malignant
"""
with open(yaml_4class, "w") as f:
    f.write(yaml_content.strip())

print(f"\ndataset_4class.yaml written to: {yaml_4class}")

# ============================================================
# STEP 6: Verify Remapping is Correct + Write dataset.yaml
#
# Before training, ALWAYS verify the remap worked correctly.
# This catches silent bugs that would destroy model accuracy.
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image

def verify_remapping(output_base, class_names, n_samples=3):
    """
    Spot-check remapped labels by:
    1. Scanning all label files and counting class IDs found
    2. Confirming no raw 'wrong' IDs survived the remap
    3. Visualizing random samples with drawn bounding boxes
    """
    print("Scanning unified label files for class ID distribution...\n")

    all_class_counts = {}
    total_boxes      = 0
    problem_files    = []

    for split in ["train", "val", "test"]:
        lbl_dir = os.path.join(output_base, "labels", split)
        lbl_files = glob.glob(os.path.join(lbl_dir, "*.txt"))

        for lf in lbl_files:
            boxes = read_yolo_label(lf)
            for (cid, *_) in boxes:
                all_class_counts[cid] = all_class_counts.get(cid, 0) + 1
                total_boxes += 1
                # Flag any class ID outside expected range 0–5
                if cid not in class_names:
                    problem_files.append((lf, cid))

    print(f"Total bounding boxes scanned : {total_boxes}")
    print(f"\nClass ID distribution after remapping:")
    print(f"{'ID':<5} {'Name':<30} {'Boxes':<8} {'%'}")
    print("─" * 55)
    for cid in sorted(class_names.keys()):
        count = all_class_counts.get(cid, 0)
        pct   = 100 * count / total_boxes if total_boxes > 0 else 0
        bar   = "█" * int(pct / 2)
        print(f"  {cid}  {class_names[cid]:<28} {count:<8} {pct:5.1f}%  {bar}")

    # Report problems
    if problem_files:
        print(f"\n⚠️  PROBLEM: {len(problem_files)} boxes have unexpected class IDs!")
        for (f, cid) in problem_files[:5]:
            print(f"   File: {f}  |  Bad class_id: {cid}")
    else:
        print(f"\n✅ All class IDs in range 0–{max(class_names.keys())} — remap successful!")

    return all_class_counts


def visualize_remapped_sample(output_base, class_names, n_samples=6):
    """
    Draw bounding boxes on random images from the unified train set.
    Visually confirms boxes look correct after remapping.
    """
    # Color per unified class
    colors = {
        0: "cyan",    # sickle
        1: "red",     # malaria
        2: "lime",    # leukemia benign
        3: "yellow",  # leukemia malignant early
        4: "orange",  # leukemia malignant pre
        5: "magenta", # leukemia malignant pro
    }

    img_dir = os.path.join(output_base, "images", "train")
    lbl_dir = os.path.join(output_base, "labels", "train")

    all_imgs = (
        glob.glob(os.path.join(img_dir, "*.jpg")) +
        glob.glob(os.path.join(img_dir, "*.jpeg"))
    )
    samples = random.sample(all_imgs, min(n_samples, len(all_imgs)))

    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    axes = axes.flatten()

    for i, img_path in enumerate(samples):
        lbl_path = os.path.join(
            lbl_dir,
            os.path.splitext(os.path.basename(img_path))[0] + ".txt"
        )

        img    = Image.open(img_path).convert("RGB")
        img_w, img_h = img.size
        boxes  = read_yolo_label(lbl_path)

        ax = axes[i]
        ax.imshow(img)
        ax.axis("off")

        class_ids_in_image = set()
        for (cid, xc, yc, bw, bh) in boxes:
            # Convert YOLO normalized → pixel
            x1 = (xc - bw / 2) * img_w
            y1 = (yc - bh / 2) * img_h
            pw = bw * img_w
            ph = bh * img_h

            color = colors.get(cid, "white")
            rect  = patches.Rectangle(
                (x1, y1), pw, ph,
                linewidth=1.5, edgecolor=color, facecolor="none"
            )
            ax.add_patch(rect)
            class_ids_in_image.add(cid)

        labels_str = ", ".join([class_names[c] for c in sorted(class_ids_in_image)])
        ax.set_title(f"{os.path.basename(img_path)}\nClasses: {labels_str}", fontsize=8)

    plt.suptitle("Remapping Verification — Unified Train Set", fontsize=12, y=1.01)
    plt.tight_layout()
    plt.show()


# ── Run verification ─────────────────────────────────────────
class_counts = verify_remapping(OUTPUT_BASE, CLASS_NAMES_UNIFIED)
visualize_remapped_sample(OUTPUT_BASE, CLASS_NAMES_UNIFIED, n_samples=6)

# ── Write dataset.yaml ───────────────────────────────────────
yaml_content = f"""
# Multi-Disease Blood Cell Detection — Unified 6-Class Dataset
# Generated automatically — do not edit class order!

path: {OUTPUT_BASE}

train: images/train
val:   images/val
test:  images/test

# 6 classes total
nc: 6

# Class names — ORDER MUST MATCH unified IDs above
names:
  0: sickle
  1: malaria
  2: leukemia_benign
  3: leukemia_malignant_early
  4: leukemia_malignant_pre
  5: leukemia_malignant_pro
"""

yaml_path = "/kaggle/working/dataset.yaml"
with open(yaml_path, "w") as f:
    f.write(yaml_content.strip())

print(f"\n✅ dataset.yaml written to: {yaml_path}")
print(yaml_content.strip())

# ── Final file count check ────────────────────────────────────
print(f"\n{'='*50}")
print("FINAL DATASET FILE COUNT CHECK")
print(f"{'='*50}")
for split in ["train", "val", "test"]:
    n_imgs = len(
        glob.glob(f"{OUTPUT_BASE}/images/{split}/*.jpg") +
        glob.glob(f"{OUTPUT_BASE}/images/{split}/*.jpeg")
    )
    n_lbls = len(glob.glob(f"{OUTPUT_BASE}/labels/{split}/*.txt"))
    status = "✅" if n_imgs == n_lbls else "⚠️  MISMATCH"
    print(f"  {split:5s}: {n_imgs} images  |  {n_lbls} labels  {status}")

# ============================================================
# STEP 7 (UPDATED): Train YOLOv8s on the 6-class dataset
#
# KEY CHANGES vs the previous version:
#   - nc: 6  (not 4) — reflected automatically via dataset.yaml
#   - copy_paste augmentation increased: helps malaria (minority class)
#   - cls weight tuning explained below
# ============================================================

from ultralytics import YOLO

model = YOLO("yolov8s.pt")   # Pretrained on COCO — fine-tunes fast

print("Starting training on unified 6-class dataset...")
print(f"YAML: {yaml_path}\n")

results = model.train(
    data         = yaml_path,
    epochs       = 100,
    imgsz        = 640,
    batch        = 16,          # Reduce to 8 if you get CUDA OOM

    # ── Optimizer ─────────────────────────────────────────────
    optimizer    = "AdamW",
    lr0          = 0.001,
    lrf          = 0.01,
    weight_decay = 0.0005,

    # ── Transfer learning ──────────────────────────────────────
    # Freeze backbone for first ~10 epochs so pretrained features
    # don't get destroyed by the new task's gradients
    freeze       = 10,

    # ── Augmentation — tuned for microscopy images ─────────────
    hsv_h        = 0.01,        # Very slight hue shift (images are near-grayscale)
    hsv_s        = 0.3,         # Moderate saturation
    hsv_v        = 0.5,         # Brightness — IMPORTANT: microscopy varies a lot
    degrees      = 45,          # Rotation — valid, cells are round
    translate    = 0.1,
    scale        = 0.5,
    shear        = 5.0,
    flipud       = 0.5,         # Vertical flip — valid for blood smears
    fliplr       = 0.5,
    mosaic       = 1.0,         # Mosaic: tiles 4 images together — great for small datasets
    mixup        = 0.15,        # MixUp: blends pairs of images
    copy_paste   = 0.3,         # INCREASED: copies objects between images
                                 # Especially helps malaria (fewest boxes)

    # ── Class imbalance strategy ───────────────────────────────
    # YOLOv8 handles class imbalance through loss weighting.
    # The 'cls' hyperparameter controls classification loss weight.
    # We leave it at default (0.5) — the main tool is augmentation.
    # If malaria AP is still low after training, increase copy_paste to 0.5.

    # ── Early stopping & checkpointing ────────────────────────
    patience     = 25,          # Stop if no mAP improvement for 25 epochs
    save         = True,
    save_period  = 10,          # Extra checkpoint every 10 epochs

    # ── Output ────────────────────────────────────────────────
    project      = "/kaggle/working/runs",
    name         = "parasite_v1_6class",

    # ── Hardware ──────────────────────────────────────────────
    device       = [0,1],           # GPU 0 = Kaggle T4
    workers      = 2,
    seed         = 42,
    plots        = True,
    verbose      = True,
)

print("\n✅ Training complete!")
best_model_path = f"/kaggle/working/runs/parasite_v1_6class/weights/best.pt"
print(f"Best model: {best_model_path}")

# ============================================================
# STEP 8 (UPDATED): Evaluate with per-class AP breakdown
# ============================================================

from ultralytics import YOLO

best_model_path = "/kaggle/working/runs/parasite_v1_6class/weights/best.pt"
eval_model      = YOLO(best_model_path)

CLASS_NAMES_LIST = [
    "sickle",
    "malaria",
    "leukemia_benign",
    "leukemia_malignant_early",
    "leukemia_malignant_pre",
    "leukemia_malignant_pro",
]

# ── Validation set evaluation ────────────────────────────────
val_results = eval_model.val(
    data      = yaml_path,
    split     = "val",
    imgsz     = 640,
    batch     = 16,
    conf      = 0.25,
    iou       = 0.50,
    plots     = True,
    save_json = True,
    project   = "/kaggle/working/runs",
    name      = "eval_val_6class",
)

# ── Print per-class metrics ──────────────────────────────────
print(f"\n{'='*60}")
print("VALIDATION RESULTS — PER CLASS")
print(f"{'='*60}")
print(f"{'Class':<30} {'AP@50':>8}")
print("─" * 40)

for i, name in enumerate(CLASS_NAMES_LIST):
    try:
        ap50 = val_results.box.ap50[i]
        # Flag malaria separately — it's the main parasite class
        flag = " ← PARASITE" if name == "malaria" else ""
        print(f"  {name:<28} {ap50:8.4f}{flag}")
    except IndexError:
        print(f"  {name:<28} {'N/A':>8}  (no detections)")

print("─" * 40)
print(f"  {'mAP@50 (mean)':<28} {val_results.box.map50:8.4f}")
print(f"  {'mAP@50-95':<28} {val_results.box.map:8.4f}")
print(f"  {'Mean Precision':<28} {val_results.box.mp:8.4f}")
print(f"  {'Mean Recall':<28} {val_results.box.mr:8.4f}")

# ── Interpretation guide ────────────────────────────────────
print(f"""
INTERPRETING YOUR RESULTS:
─────────────────────────────────────────────────────
  mAP@50 > 0.85  → Excellent for this dataset size
  mAP@50 > 0.75  → Good — ready for research use
  mAP@50 > 0.60  → Acceptable — needs improvement

  If malaria AP is lowest (expected — fewest images):
    → Increase copy_paste to 0.5 and retrain
    → Or use weighted sampling (explained below)

  If leukemia_benign AP is low:
    → Check that class 0 in leukemia labels is truly benign
    → Visualize those boxes with Step 6 verification code
""")

# ============================================================
# FIX B: Lower the detection threshold specifically for 'pre'
#
# WHY this helps for MISSED boxes:
# The objectness score for 'pre' cells sits just below the
# 0.25 detection threshold. If we lower it to 0.15 for class 4,
# the model will start proposing boxes that it previously
# suppressed. Some will be wrong (lower precision), but recall
# will jump sharply.
#
# This is a POST-PROCESSING fix — no retraining needed.
# Apply it immediately on the existing v1 model to get a
# quick benchmark before the retrain finishes.
# ============================================================

from ultralytics import YOLO
from PIL import Image, ImageDraw
import glob, os, pandas as pd

BEST_MODEL  = "/kaggle/working/runs/parasite_v1_6class/weights/best.pt"
OUTPUT_BASE = "/kaggle/working/unified_dataset"

CLASS_NAMES = {
    0:"sickle", 1:"malaria", 2:"leukemia_benign",
    3:"leukemia_malignant_early", 4:"leukemia_malignant_pre",
    5:"leukemia_malignant_pro"
}
CLASS_COLORS = {
    0:(100,220,255), 1:(255,60,60), 2:(60,200,60),
    3:(255,200,30),  4:(255,130,30), 5:(210,80,210)
}

# Per-class confidence thresholds (tuned based on our analysis)
PER_CLASS_CONF = {
    0: 0.25,   # sickle       — default, performing well
    1: 0.40,   # malaria      — raised, reduce false positives
    2: 0.25,   # benign       — default, performing well
    3: 0.25,   # early        — default, performing well
    4: 0.15,   # pre          — LOWERED, catch missed detections
    5: 0.25,   # pro          — default, performing well
}


def predict_per_class_threshold(image_path, model, per_class_conf,
                                 iou_threshold=0.45):
    """
    Run inference at a very low global conf (0.10) to get all
    candidate boxes, then filter each by its class-specific threshold.

    This lets different classes have different sensitivity levels
    without retraining anything.
    """
    # Get all candidates at low global threshold
    result = model.predict(
        image_path,
        conf    = 0.10,   # Very low — we filter manually below
        iou     = iou_threshold,
        imgsz   = 640,
        verbose = False
    )[0]

    img    = Image.open(image_path).convert("RGB")
    iw, ih = img.size

    kept  = []
    total_candidates = len(result.boxes)

    for box in result.boxes:
        cid  = int(box.cls[0])
        conf = float(box.conf[0])

        # Apply per-class threshold
        min_conf = per_class_conf.get(cid, 0.25)
        if conf < min_conf:
            continue

        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
        kept.append({
            "class_id"  : cid,
            "class_name": CLASS_NAMES[cid],
            "confidence": round(conf, 4),
            "x1": int(x1), "y1": int(y1),
            "x2": int(x2), "y2": int(y2),
        })

    return kept, total_candidates


def visualize_per_class_thresh(image_path, model, per_class_conf):
    """
    Show side-by-side: standard threshold vs per-class threshold.
    Focus on 'pre' cells — they should appear on the right but
    be absent or fewer on the left.
    """
    import matplotlib.pyplot as plt
    import matplotlib.patches as patches

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    titles = [
        ("Standard (conf=0.25 all)", {c: 0.25 for c in range(6)}),
        ("Per-class thresholds",     per_class_conf),
    ]

    for ax, (title, conf_map) in zip(axes, titles):
        detections, _ = predict_per_class_threshold(
            image_path, model, conf_map
        )

        img = Image.open(image_path).convert("RGB")
        iw, ih = img.size

        ax.imshow(img)
        ax.set_title(title, fontsize=10)
        ax.axis("off")

        pre_count = 0
        for d in detections:
            cid   = d["class_id"]
            color = tuple(c/255 for c in CLASS_COLORS[cid])
            rect  = patches.Rectangle(
                (d["x1"], d["y1"]),
                d["x2"] - d["x1"],
                d["y2"] - d["y1"],
                linewidth = 2 if cid == 4 else 1,
                edgecolor = color,
                facecolor = "none",
                linestyle = "--" if cid == 4 else "-"
            )
            ax.add_patch(rect)
            if cid == 4:
                pre_count += 1
                ax.text(d["x1"], d["y1"] - 3,
                        f"pre {d['confidence']:.2f}",
                        color=color, fontsize=7, fontweight="bold",
                        bbox=dict(boxstyle="round,pad=0.1",
                                  facecolor="black", alpha=0.6))

        total = len(detections)
        ax.set_xlabel(
            f"{total} detections  |  'pre' boxes: {pre_count}",
            fontsize=9
        )

    plt.suptitle(
        "Effect of per-class confidence thresholds\n"
        "'pre' cells shown with dashed orange boxes",
        fontsize=11, y=1.02
    )
    plt.tight_layout()
    plt.show()


# ── Load model and test ──────────────────────────────────────
model = YOLO(BEST_MODEL)

# Find a validation image that contains 'pre' cells
def find_pre_val_images(output_base, n=3):
    results = []
    lbl_dir = os.path.join(output_base, "labels", "val")
    img_dir = os.path.join(output_base, "images", "val")
    for lf in glob.glob(os.path.join(lbl_dir, "*.txt")):
        boxes = read_yolo_label(lf)
        if any(b[0] == 4 for b in boxes):
            base = os.path.splitext(os.path.basename(lf))[0]
            imgs = (glob.glob(os.path.join(img_dir, base + ".jpg")) +
                    glob.glob(os.path.join(img_dir, base + ".jpeg")))
            if imgs:
                results.append(imgs[0])
                if len(results) >= n:
                    break
    return results


pre_val_imgs = find_pre_val_images(OUTPUT_BASE, n=3)
print(f"Found {len(pre_val_imgs)} val images with 'pre' cells\n")

for img_path in pre_val_imgs:
    print(f"Image: {os.path.basename(img_path)}")
    visualize_per_class_thresh(img_path, model, PER_CLASS_CONF)

# ============================================================
# STEP 9: If malaria AP is low — apply class-weighted sampling
#
# This is an OPTIONAL extra step.
# Run this only if Step 8 shows malaria AP < 0.50 after training.
#
# Strategy: oversample malaria images so the model sees them
# more frequently during training. This is done via repeat_mosaic.
# ============================================================

def oversample_minority_class(output_base, disease="malaria",
                               img_ext=".jpg", factor=3):
    """
    Duplicate images of the minority class in the training set.
    factor=3 means malaria images appear 3x more often than once.

    This is simpler than weighted loss — just more copies of the
    underrepresented class in the training folder.
    """
    img_dir = os.path.join(output_base, "images", "train")
    lbl_dir = os.path.join(output_base, "labels", "train")

    # Find all training images that contain class 1 (malaria)
    malaria_imgs = []
    all_lbls     = glob.glob(os.path.join(lbl_dir, "*.txt"))

    for lbl_path in all_lbls:
        boxes = read_yolo_label(lbl_path)
        if any(cid == 1 for (cid, *_) in boxes):   # class 1 = malaria
            base  = os.path.splitext(os.path.basename(lbl_path))[0]
            img_candidates = (
                glob.glob(os.path.join(img_dir, base + ".jpg")) +
                glob.glob(os.path.join(img_dir, base + ".jpeg"))
            )
            if img_candidates:
                malaria_imgs.append((img_candidates[0], lbl_path))

    print(f"Found {len(malaria_imgs)} malaria training images.")
    print(f"Duplicating each {factor - 1} extra time(s)...\n")

    added = 0
    for (img_path, lbl_path) in malaria_imgs:
        ext = os.path.splitext(img_path)[1]
        for copy_n in range(1, factor):
            # Find the index from the existing filename to continue numbering
            # New name: original_name + _aug_N
            base = os.path.splitext(os.path.basename(img_path))[0]
            new_base     = f"{base}_aug{copy_n}"
            new_img_path = os.path.join(img_dir, new_base + ext)
            new_lbl_path = os.path.join(lbl_dir, new_base + ".txt")

            shutil.copy2(img_path, new_img_path)
            shutil.copy2(lbl_path, new_lbl_path)
            added += 1

    print(f"Added {added} malaria image copies to training set.")
    print(f"New malaria training count: {len(malaria_imgs) * factor}")

    # Verify new totals
    n_imgs = len(glob.glob(os.path.join(img_dir, "*.jpg")))
    n_lbls = len(glob.glob(os.path.join(lbl_dir, "*.txt")))
    print(f"\nUpdated train set: {n_imgs} images, {n_lbls} labels")


# ── Only run this if malaria AP < 0.50 from Step 8 ───────────
# oversample_minority_class(OUTPUT_BASE, factor=3)

# Then retrain from Step 7 — the model will see more malaria examples.

# ============================================================
# FIX 1A: Diagnose what the model confuses 'pre' with
# Run this FIRST before changing anything.
# ============================================================

import os
import glob
import torch
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
from ultralytics import YOLO

BEST_MODEL   = "/kaggle/working/runs/parasite_v1_6class/weights/best.pt"
OUTPUT_BASE  = "/kaggle/working/unified_dataset"
yaml_path    = "/kaggle/working/dataset.yaml"

CLASS_NAMES = {
    0: "sickle",
    1: "malaria",
    2: "leukemia_benign",
    3: "leukemia_malignant_early",
    4: "leukemia_malignant_pre",     # <- the broken class
    5: "leukemia_malignant_pro",
}

# Colors for drawing boxes
CLASS_COLORS = {
    0: (100, 220, 255),   # sickle         → cyan
    1: (255,  80,  80),   # malaria         → red
    2: (100, 220, 100),   # benign          → green
    3: (255, 210,  50),   # malignant early → yellow
    4: (255, 120,  30),   # malignant pre   → orange (the problem class)
    5: (210,  80, 210),   # malignant pro   → purple
}

model = YOLO(BEST_MODEL)


def find_images_with_class(label_dir, class_id, img_dir, max_images=20):
    """
    Returns list of (img_path, lbl_path) for images
    that contain at least one ground truth box of class_id.
    """
    results = []
    lbl_files = glob.glob(os.path.join(label_dir, "*.txt"))

    for lf in lbl_files:
        with open(lf) as f:
            lines = f.readlines()
        cids = [int(l.split()[0]) for l in lines if l.strip()]
        if class_id in cids:
            base = os.path.splitext(os.path.basename(lf))[0]
            imgs = (
                glob.glob(os.path.join(img_dir, base + ".jpg")) +
                glob.glob(os.path.join(img_dir, base + ".jpeg"))
            )
            if imgs:
                results.append((imgs[0], lf))
            if len(results) >= max_images:
                break
    return results


def draw_gt_and_pred(img_path, lbl_path, model, class_names, colors, conf=0.20):
    """
    Returns a side-by-side figure:
      Left  = Ground Truth boxes
      Right = Model Predictions
    Lets you visually see what the model predicts vs what is correct.
    """
    img      = Image.open(img_path).convert("RGB")
    img_w, img_h = img.size

    # Read ground truth
    gt_boxes = []
    with open(lbl_path) as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) < 5:
                continue
            cid = int(parts[0])
            xc, yc, bw, bh = map(float, parts[1:5])
            x1 = (xc - bw / 2) * img_w
            y1 = (yc - bh / 2) * img_h
            gt_boxes.append((cid, x1, y1, bw * img_w, bh * img_h))

    # Run model
    results  = model.predict(img_path, conf=conf, verbose=False)[0]
    pred_boxes = []
    for box in results.boxes:
        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
        pred_boxes.append((
            int(box.cls[0]), float(box.conf[0]),
            x1, y1, x2 - x1, y2 - y1
        ))

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    for ax, (boxes, title, show_conf) in zip(axes, [
        (gt_boxes,   "Ground Truth",   False),
        (pred_boxes, "Model Prediction", True),
    ]):
        ax.imshow(img)
        ax.set_title(title, fontsize=11)
        ax.axis("off")

        if show_conf:
            for (cid, conf_val, x1, y1, bw, bh) in boxes:
                color = tuple(c / 255 for c in colors.get(cid, (255,255,255)))
                rect  = patches.Rectangle(
                    (x1, y1), bw, bh,
                    linewidth=1.5, edgecolor=color, facecolor="none"
                )
                ax.add_patch(rect)
                ax.text(x1, y1 - 3,
                        f"{class_names[cid]} {conf_val:.2f}",
                        color=color, fontsize=7, fontweight="bold",
                        bbox=dict(boxstyle="round,pad=0.1",
                                  facecolor="black", alpha=0.5))
        else:
            for (cid, x1, y1, bw, bh) in boxes:
                color = tuple(c / 255 for c in colors.get(cid, (255,255,255)))
                rect  = patches.Rectangle(
                    (x1, y1), bw, bh,
                    linewidth=1.5, edgecolor=color, facecolor="none"
                )
                ax.add_patch(rect)
                ax.text(x1, y1 - 3,
                        class_names[cid],
                        color=color, fontsize=7, fontweight="bold",
                        bbox=dict(boxstyle="round,pad=0.1",
                                  facecolor="black", alpha=0.5))

    plt.suptitle(os.path.basename(img_path), fontsize=9, y=1.01)
    plt.tight_layout()
    plt.show()

    # Print confusion for this image
    gt_ids   = [b[0] for b in gt_boxes]
    pred_ids = [b[0] for b in pred_boxes]
    print(f"  GT classes   : {[class_names[c] for c in gt_ids]}")
    print(f"  Pred classes : {[class_names[c] for c in pred_ids]}")
    print()


# ── Run diagnosis on the 'pre' class ─────────────────────────
print("Diagnosing leukemia_malignant_pre failures...\n")
print("Showing GT vs Prediction for images containing 'pre' cells.")
print("Look at RIGHT panel — what class does the model predict instead?\n")

pre_images = find_images_with_class(
    label_dir = f"{OUTPUT_BASE}/labels/val",
    img_dir   = f"{OUTPUT_BASE}/images/val",
    class_id  = 4,  # leukemia_malignant_pre
    max_images= 6,
)

for (img_path, lbl_path) in pre_images:
    draw_gt_and_pred(img_path, lbl_path, model, CLASS_NAMES, CLASS_COLORS, conf=0.20)

# FIX 1B: Build a confusion matrix manually
# ============================================================

from collections import defaultdict

def compute_class_confusion(model, label_dir, img_dir, class_names, conf_threshold=0.25, iou_threshold=0.45):
    """
    For every ground truth box, find the best matching predicted box
    (by IoU). Record: what was GT class? What did model predict?

    Returns a confusion dict: { (gt_class, pred_class): count }
    """
    def box_iou(b1, b2):
        """Compute IoU between two boxes [x1,y1,x2,y2]."""
        xi1 = max(b1[0], b2[0])
        yi1 = max(b1[1], b2[1])
        xi2 = min(b1[2], b2[2])
        yi2 = min(b1[3], b2[3])
        inter = max(0, xi2 - xi1) * max(0, yi2 - yi1)
        area1 = (b1[2]-b1[0]) * (b1[3]-b1[1])
        area2 = (b2[2]-b2[0]) * (b2[3]-b2[1])
        union = area1 + area2 - inter
        return inter / union if union > 0 else 0.0

    confusion = defaultdict(int)
    lbl_files = glob.glob(os.path.join(label_dir, "*.txt"))

    for lf in lbl_files:
        base = os.path.splitext(os.path.basename(lf))[0]
        imgs = (
            glob.glob(os.path.join(img_dir, base + ".jpg")) +
            glob.glob(os.path.join(img_dir, base + ".jpeg"))
        )
        if not imgs:
            continue

        img    = Image.open(imgs[0])
        img_w, img_h = img.size

        # Ground truth boxes (pixel coords)
        gt = []
        with open(lf) as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) < 5:
                    continue
                cid  = int(parts[0])
                xc, yc, bw, bh = map(float, parts[1:5])
                x1 = (xc - bw/2) * img_w
                y1 = (yc - bh/2) * img_h
                x2 = (xc + bw/2) * img_w
                y2 = (yc + bh/2) * img_h
                gt.append((cid, [x1, y1, x2, y2]))

        # Predictions
        preds_raw = model.predict(imgs[0], conf=conf_threshold, verbose=False)[0]
        preds = []
        for box in preds_raw.boxes:
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
            preds.append((int(box.cls[0]), float(box.conf[0]), [x1,y1,x2,y2]))

        # Match each GT box to the best-IoU prediction
        for (gt_cid, gt_box) in gt:
            best_iou    = 0.0
            best_pred   = None
            for (pred_cid, pred_conf, pred_box) in preds:
                iou = box_iou(gt_box, pred_box)
                if iou > best_iou:
                    best_iou  = iou
                    best_pred = pred_cid

            if best_iou >= iou_threshold and best_pred is not None:
                confusion[(gt_cid, best_pred)] += 1  # matched
            else:
                confusion[(gt_cid, -1)] += 1          # missed (false negative)

    return confusion


# ── DEFINE class_names BEFORE calling the function ──
class_names = {
    0: "sickle",
    1: "malaria",
    2: "leukemia_benign",
    3: "leukemia_malignant_early",
    4: "leukemia_malignant_pre",
    5: "leukemia_malignant_pro"
}

print("Computing confusion matrix on validation set...\n")
confusion = compute_class_confusion(
    model       = model,
    label_dir   = f"{OUTPUT_BASE}/labels/val",
    img_dir     = f"{OUTPUT_BASE}/images/val",
    class_names = class_names  # ✅ Pass it explicitly
)

# ── Print confusion for class 4 (pre) ────────────────────────
print("=" * 55)
print("WHERE DOES 'leukemia_malignant_pre' GET CONFUSED?")
print("=" * 55)
print(f"{'Predicted as':<30} {'Count':>6}")
print("─" * 38)

pre_rows = {k: v for k, v in confusion.items() if k[0] == 4}
total    = sum(pre_rows.values())

for (gt_cid, pred_cid), count in sorted(pre_rows.items(), key=lambda x: -x[1]):
    pred_name = class_names.get(pred_cid, "MISSED") if pred_cid != -1 else "MISSED (no match)"
    pct       = 100 * count / total if total else 0
    bar       = "█" * int(pct / 5)
    print(f"  {pred_name:<28} {count:>4}  {pct:5.1f}%  {bar}")

print(f"\n  Total GT 'pre' boxes matched: {total}")
print("""
READING THIS TABLE:
─────────────────────────────────────────
If you see:
  'leukemia_malignant_early' = 40%  → model confuses pre with early
  'MISSED'                   = 50%  → model simply doesn't detect pre at all
  'leukemia_benign'          = 10%  → some confusion with benign

This tells us exactly which fix to apply (see Fix 1C below).
""")

# ============================================================
# FIX C — Retrain from best.pt with label smoothing
#
# WHERE IT FITS: Run this AFTER Fix A, replaces Step 7.
#
# WHY WARM START FROM best.pt?
#   Cold start (yolov8s.pt) would take ~100 epochs to converge.
#   Starting from best.pt means the backbone already understands
#   blood cell morphology. We only need ~60–70 epochs to push
#   the objectness head to fire on 'pre' cells that it currently
#   misses. This saves ~30 minutes of GPU time.
#
# KEY CHANGE — label_smoothing = 0.1
#   Without smoothing, the training signal for 'pre' is binary:
#   fire at 1.0 confidence or not at all. Because 'pre' cells
#   are rare in the original data, "not at all" wins every time.
#   Smoothing softens targets to 0.9 / 0.1, forcing the objectness
#   head to maintain a weak signal even on borderline cells.
#   This is the single most impactful change for missed detections.
#
# OTHER CHANGES vs original Step 7:
#   lr0   : 0.001 → 0.0003  (fine-tuning, not relearning)
#   epochs: 100   → 70      (warm start converges faster)
#   degrees: 45  → 90       (cells are round — full rotation valid)
#   scale : 0.5  → 0.6      (slightly wider zoom jitter)
# ============================================================

from ultralytics import YOLO

# ── Paths ────────────────────────────────────────────────────
BEST_V1   = "/kaggle/working/runs/parasite_v1_6class/weights/best.pt"
yaml_path = "/kaggle/working/dataset.yaml"
SAVE_DIR  = "/kaggle/working/runs"
RUN_NAME  = "parasite_v2_fixed"

# ── Confirm inputs exist before wasting GPU time ─────────────
import os
assert os.path.exists(BEST_V1),   f"best.pt not found: {BEST_V1}"
assert os.path.exists(yaml_path), f"dataset.yaml not found: {yaml_path}"

print("Fix C — Starting retraining")
print(f"  Warm start  : {BEST_V1}")
print(f"  Dataset     : {yaml_path}")
print(f"  Output name : {RUN_NAME}")
print(f"  Estimated time on T4: 30–40 minutes\n")

# ── Load from best.pt ─────────────────────────────────────────
# This is the key line. YOLO("yolov8s.pt") = cold start.
# YOLO(BEST_V1)           = warm start from your trained weights.
model_v2 = YOLO(BEST_V1)

# ── Train ─────────────────────────────────────────────────────
results_v2 = model_v2.train(
    data    = yaml_path,
    epochs  = 70,
    imgsz   = 640,
    batch   = 16,            # Reduce to 8 if you see CUDA OOM

    # ── Optimizer ───────────────────────────────────────────
    optimizer    = "AdamW",
    lr0          = 0.0003,   # 3× lower than original — fine-tuning LR
    lrf          = 0.01,     # Final LR = lr0 × lrf = 0.000003
    weight_decay = 0.0005,

    # ── THE KEY FIX: label smoothing ────────────────────────
    # Converts hard 0/1 objectness targets to soft 0.05/0.95.
    # Stops the objectness head from completely ignoring
    # cells it is uncertain about (which is exactly what was
    # happening to 'pre' cells — 63.8% MISSED).
    label_smoothing = 0.1,

    # ── Augmentation ────────────────────────────────────────
    hsv_h     = 0.01,        # Very subtle hue — near-grayscale images
    hsv_s     = 0.3,
    hsv_v     = 0.5,         # Brightness important for microscopy
    degrees   = 90,          # Full rotation — cells are rotationally symmetric
    translate = 0.1,
    scale     = 0.6,         # Wider zoom jitter than v1 (was 0.5)
    shear     = 5.0,
    flipud    = 0.5,
    fliplr    = 0.5,
    mosaic    = 1.0,         # Tiles 4 images — critical for small datasets
    mixup     = 0.15,
    copy_paste= 0.3,

    # ── Early stopping and checkpoints ──────────────────────
    patience    = 20,        # Stop if no mAP gain for 20 epochs
    save        = True,
    save_period = 10,        # Extra checkpoint every 10 epochs

    # ── Output ──────────────────────────────────────────────
    project  = SAVE_DIR,
    name     = RUN_NAME,

    # ── Hardware ────────────────────────────────────────────
    device   = [0,1],            # GPU 0 — Kaggle T4
    workers  = 2,
    seed     = 42,
    plots    = True,         # Saves loss curves + PR curves automatically
    verbose  = True,
)

# ── Report where outputs are ─────────────────────────────────
BEST_V2 = f"{SAVE_DIR}/{RUN_NAME}/weights/best.pt"
LAST_V2 = f"{SAVE_DIR}/{RUN_NAME}/weights/last.pt"

print("\n" + "=" * 55)
print("Fix C complete")
print("=" * 55)
print(f"  Best checkpoint : {BEST_V2}")
print(f"  Last checkpoint : {LAST_V2}")
print(f"  Training plots  : {SAVE_DIR}/{RUN_NAME}/results.png")
print(f"\nAlways use best.pt for evaluation, not last.pt.")

# ============================================================
# EVALUATION — compare v1 vs v2 side by side
# ============================================================

from ultralytics import YOLO

BEST_V1   = "/kaggle/working/runs/parasite_v1_6class/weights/best.pt"
BEST_V2   = "/kaggle/working/runs/parasite_v2_fixed/weights/best.pt"
yaml_path = "/kaggle/working/dataset.yaml"

CLASS_NAMES_LIST = [
    "sickle",
    "malaria",
    "leukemia_benign",
    "leukemia_malignant_early",
    "leukemia_malignant_pre",
    "leukemia_malignant_pro",
]

def run_val(model_path, label, conf=0.25):
    print(f"Evaluating {label}...")
    m = YOLO(model_path)
    r = m.val(
        data    = yaml_path,
        split   = "val",
        imgsz   = 640,
        conf    = conf,
        iou     = 0.50,
        verbose = False,
        project = "/kaggle/working/runs",
        name    = f"eval_{label}",
    )
    return r

r_v1 = run_val(BEST_V1, "v1")
r_v2 = run_val(BEST_V2, "v2")

# ── Print comparison ─────────────────────────────────────────
print(f"\n{'='*62}")
print(f"  RESULTS: v1 (original) vs v2 (Fix A + Fix C)")
print(f"{'='*62}")
print(f"  {'Class':<30} {'v1 AP@50':>9} {'v2 AP@50':>9} {'change':>8}")
print("  " + "─" * 58)

for i, name in enumerate(CLASS_NAMES_LIST):
    try:
        ap1   = r_v1.box.ap50[i]
        ap2   = r_v2.box.ap50[i]
        delta = ap2 - ap1
        arrow = "▲" if delta >  0.005 else ("▼" if delta < -0.005 else "─")
        flag  = "  ← was broken" if name == "leukemia_malignant_pre" else (
                "  ← watch"     if name == "malaria"                 else "")
        print(f"  {name:<30} {ap1:9.4f} {ap2:9.4f} "
              f" {arrow}{abs(delta):.4f}{flag}")
    except IndexError:
        print(f"  {name:<30} {'N/A':>9} {'N/A':>9}")

print("  " + "─" * 58)
map1 = r_v1.box.map50
map2 = r_v2.box.map50
arrow = "▲" if map2 > map1 else "▼"
print(f"  {'mAP@50':<30} {map1:9.4f} {map2:9.4f}  {arrow}{abs(map2-map1):.4f}")
print(f"  {'Precision':<30} {r_v1.box.mp:9.4f} {r_v2.box.mp:9.4f}")
print(f"  {'Recall':<30} {r_v1.box.mr:9.4f} {r_v2.box.mr:9.4f}")

print(f"""
  What to look for:
  ─────────────────────────────────────────────────────
  leukemia_malignant_pre  target: 0.135 → 0.45–0.60
  malaria                 target: 0.691 → 0.72–0.78
  Other 4 classes         should not drop more than 0.02

  If 'pre' is still below 0.35:
    Share the result here and we will decide whether
    to merge early+pre+pro into one malignant class.
""")

# ============================================================
# FIX E: Train v3 on the merged 4-class dataset
#
# Starting from best.pt (v2) — already understands blood cells.
# Only needs to learn "malignant = any of early/pre/pro".
# Expected to converge quickly — likely best checkpoint
# appears around epoch 30–40.
# ============================================================

from ultralytics import YOLO

BEST_V2   = "/kaggle/working/runs/parasite_v2_fixed-3/weights/best.pt"
yaml_4cls = "/kaggle/working/dataset_4class.yaml"

# ── Confirm paths ─────────────────────────────────────────────
assert os.path.exists(BEST_V2),   f"v2 best.pt not found: {BEST_V2}"
assert os.path.exists(yaml_4cls), f"yaml not found: {yaml_4cls}"

print("Fix E — Training v3 on 4-class merged dataset")
print(f"  Warm start : {BEST_V2}")
print(f"  Dataset    : {yaml_4cls}")
print(f"  Note: best.pt is from v2 (6-class). The head will")
print(f"  adapt to 4 classes automatically in first few epochs.\n")

model_v3 = YOLO(BEST_V2)

results_v3 = model_v3.train(
    data    = yaml_4cls,
    epochs  = 60,
    imgsz   = 640,
    batch   = 16,

    # ── Optimizer — same fine-tuning LR as v2 ────────────────
    optimizer    = "AdamW",
    lr0          = 0.0003,
    lrf          = 0.01,
    weight_decay = 0.0005,

    # ── Label smoothing — keep it, it helped overall ──────────
    label_smoothing = 0.1,

    # ── Augmentation — identical to v2 ────────────────────────
    hsv_h     = 0.01,
    hsv_s     = 0.3,
    hsv_v     = 0.5,
    degrees   = 90,
    translate = 0.1,
    scale     = 0.6,
    shear     = 5.0,
    flipud    = 0.5,
    fliplr    = 0.5,
    mosaic    = 1.0,
    mixup     = 0.15,
    copy_paste= 0.3,

    # ── Checkpointing ─────────────────────────────────────────
    patience    = 20,
    save        = True,
    save_period = 10,

    project  = "/kaggle/working/runs",
    name     = "parasite_v3_4class",
    device   = [0,1],
    workers  = 2,
    seed     = 42,
    plots    = True,
    verbose  = True,
)

BEST_V3 = "/kaggle/working/runs/parasite_v3_4class/weights/best.pt"
print(f"\nv3 best checkpoint: {BEST_V3}")